# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

machine:
  services:
    - docker
  post:
    - chmod +x ~/circleci-tunnel.sh
    - ~/circleci-tunnel.sh start:
        background: true

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ba:6e:00:e0:7b:f4:eb:ea:32:00:68:75:06:15:ef:7b"
      - run: ls -la
      - run: ls -la ~/.ssh/
      - run: cat ~/.ssh/id_rsa_ba6e00e07bf4ebea320068750615ef7b
      - run: ssh -i ~/.ssh/id_rsa_ba6e00e07bf4ebea320068750615ef7b -t jenkins@82.94.162.78 ls


