# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  trout:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    
    steps:
      - checkout
      - run: ls -la
#      - run: echo $(wget -qO - http://canihazip.com/s)
#      - run: ls -la
      - run:
          name: "create files"
          command: |
            mkdir folder && cd folder && touch f1 f2 f3 f4 f5
      - run: zip -r arhiva.zip folder/

      - store_artifacts:
          path: arhiva.zip
          destination: arhiva


